backlash: 128
corr_test: 0
fine_range: 200
fine_steps: 9
fine_steps_size: 50
iter_max: 2
maxmin: 0.05
method: Tenengrad
run_only_once: false
success: false
time_interval_min: 200
use_channel: 1
use_last_autofocus: false
