backlash: 128
corr_test: 1
duration_max: 10
interval_min: 100
iteration_max: 3
maxmin: 0.05
max_iterations: 10
resolution: [640,480]
roi: [1,1]
run_only_once: true
scan_method: 0
step_dist_coarse: 200
step_dist_fine: 50
steps_coarse: 2
steps_fine: 4
success: 1
technique: Tenengrad
use_channel: 1
use_last_autofocus: false