backlash: 10
camProp_defined: 1
camProp_use_global: 0
corr_test: 1
duration_max: 10
interval_min: 60
max_steps: 100
maxmin: 0.05
motor: 2
result_averaging: true
run_only_once: true
save_images: true
save_sharpness: true
scan_iterations: 1
scan_method: 0
step_dist_coarse: 10
step_dist_fine: 2
steps_coarse: 25
steps_fine: 2
success: 1
technique: Tenengrad
use_channel: 1
use_coarse_only: 1
use_last_autofocus: false
use_scipy: true
