backlash: 128
duration_max: 10
interval: 100
maxmin: 0.05
roi_size: 1024
run_only_once: true
<<<<<<< Updated upstream
step_dist_coarse: 200
step_dist_fine: 50
steps: 4
=======
save_images: false
save_sharpness: true
scan_iterations: 2
scan_method: 0
sensor_mode: 4
step_dist_coarse: 5
step_dist_fine: 1
steps_coarse: 10
steps_fine: 5
success: 1
>>>>>>> Stashed changes
technique: Tenengrad
use_channel: 1
use_last_autofocus: false
