analog_gain: 0
awbGain:
- 1.5
- 1.5
awbMode: false
camProp_defined: 0
camProp_use_global: 0
exposureCompensation: 0
exposureMode: false
image_denoise: false
iso: 100
meterMode: average
resolution:
- 3280
- 2464
sensor_mode: 0
sensor_mode_size:
- - 800
  - 480
- - 1920
  - 1080
- - 3280
  - 2464
- - 3280
  - 2464
- - 1640
  - 1232
- - 1640
  - 922
- - 1280
  - 720
- - 640
  - 480
sharpness: 0
shutterSpeed: 0
video_denoise: false
video_stabilization: false
