<<<<<<< Updated upstream
awbGain:
- 1.5
- 1.5
awbMode: auto
brightness: 50
colorEffects: null
contrast: 0
crop:
- 0.0
- 0.0
- 1.0
- 1.0
exposureCompensation: 0
exposureMode: auto
hflip: []
imageEffects: none
iso: 100
meterMode: average
previewLength: 3
=======
analog_gain: 0
awb_gain:
- 1.5
- 1.5
awb_mode: false
camProp_defined: 0
camProp_use_global: 0
exposure_compensation: 0
exposure_mode: false
image_denoise: false
iso: 100
meter_mode: average
>>>>>>> Stashed changes
resolution:
- 3280
- 2464
rotation: 0
saturation: 0
sharpness: 0
shutterSpeed: 0
vflip: false
videoStabilization: false
