awbGain:
- 1.5
- 1.5
awbMode: auto
brightness: 50
colorEffects: null
contrast: 0
crop:
- 0.0
- 0.0
- 1.0
- 1.0
exposureCompensation: 0
exposureMode: auto
hflip: []
imageEffects: none
iso: 100
meterMode: average
previewLength: 3
resolution:
- 3280
- 2464
rotation: 0
saturation: 0
sensor_mode: 0
sensor_mode_size:
- - 800
  - 480
- - 1920
  - 1080
- - 3280
  - 2464
- - 3280
  - 2464
- - 1640
  - 1232
- - 1640
  - 922
- - 1280
  - 720
- - 640
  - 480
sharpness: 0
shutterSpeed: 0
vflip: false
videoStabilization: false
