mqtt_client_name: raspi1
mqtt_client_pass: 1ipsar
mqtt_device_id_prefix: RASPI_
mqtt_device_name: RAS01
mqtt_ip: 21.3.2.52 #192.168.2.140
mqtt_keepalive: 60
mqtt_port: 1883
mqtt_use_login: false
