active: 0
active_methods:
- Custom
autofocus_num: 0
autofocus_samples: 15
autofocus_stepsize: 25
copy_path: ''
duration: 120
expt_last_image: C:\Users\rene\Documents\Programming\PPS-app\software\data\2018-12-10\expt_010\2018-12-10_Bright_0.jpg
i2c_send_delay: 0.05
image_set_num: 1
images_left: 7
images_taken: 3
images_total: 10
imaging_method: Custom
imaging_num: 0
interval: 10
interval_autofocus: 3600.0
is_autofocus: false
is_autofocus_busy: false
is_autofocus_request: false
last_expt_date: '20191126'
last_expt_num: 0
path_last_expt: C:\Users\renelachmann\Documents\Programming\UC2_Software-GIT\GUI\RASPBERRY_PI\RASPIapp_py3\data\20191126\expt_001
snap_num: 0
success: false
time_left: 53
time_passed: 22
tm_backlash: 10
tm_endPOS: 200
tm_motor: Z
tm_startPOS: 100
tm_steps: 10
tm_stepsize: 10
tm_steptime: 0.11
tm_takeimage: true
tm_totalTime: 5
