active: 0
active_camProp: null
active_methods: []
autofocus_busy: false
autofocus_new: true
autofocus_now: false
autofocus_num: 0
autofocus_samples: 15
autofocus_stepsize: 25
copy_path: ''
duration: 20
expt_last_image: C:\Users\rene\Documents\Programming\PPS-app\software\data\2018-12-10\expt_010\2018-12-10_Bright_0.jpg
i2c_send_delay: 0.05
image_set_num: 1
images_left: 13
images_taken: 0
images_total: 13
imaging_active: false
imaging_cause: MEAS
imaging_method: ''
imaging_method_dic:
  Bright: btn_imaging_technique_1
  Custom: btn_imaging_technique_3
  FPM: btn_imaging_technique_4
  Fluor: btn_imaging_technique_5
  qDPC: btn_imaging_technique_2
imaging_num: 0
interval: 5
is_autofocus: false
last_expt_date: '20200616'
last_expt_num: 2
path_last_expt: /home/uc2/UC2/UC2-GUI/data/20200616/expt_003
snap_num: 1
success: false
take_raw: 1
time_left: 116
time_passed: 4
