active: 0
active_camProp: null
active_methods: []
autofocus_busy: false
autofocus_new: true
autofocus_now: false
autofocus_num: 1
autofocus_samples: 15
autofocus_stepsize: 25
copy_path: ''
duration: 120
expt_last_image: /home/uc2/UC2/UC2-GUI/data/20200619/expt_007/20200619-MEAS-Custom--11.jpg
fluo_bayer_explizit: true
i2c_send_delay: 0.05
image_set_num: 1
images_left: 0
images_taken: 13
images_total: 13
imaging_active: false
imaging_cause: MEAS
imaging_method: Custom
imaging_method_dic:
  Bright: btn_imaging_technique_1
  Custom: btn_imaging_technique_3
  FPM: btn_imaging_technique_4
  Fluor: btn_imaging_technique_5
  qDPC: btn_imaging_technique_2
imaging_num: 12
interval: 10
is_autofocus: false
last_expt_date: '20200629'
last_expt_num: 7
path_last_expt: /home/uc2/UC2/UC2-GUI/data/20200629/expt_001
snap_num: 1
success: false
take_raw: 1
time_left: 0
time_passed: 120
tomo_active: false
