NA: 1
color:
- 255
- 255
- 255
color_picked:
- 165
- 255
- 76
color_picker_counter: 3
default:
- - &id001
    - 0
    - 0
    - 0
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
  - *id001
- - &id002
    - 0
    - 0
    - 0
  - *id002
  - *id002
  - - 255
    - 255
    - 255
  - *id002
  - - 255
    - 255
    - 255
  - - 255
    - 255
    - 255
  - *id002
- - &id003
    - 0
    - 0
    - 0
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
  - *id003
- - &id004
    - 0
    - 0
    - 0
  - *id004
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - *id004
  - *id004
  - *id004
- - &id005
    - 0
    - 0
    - 0
  - *id005
  - *id005
  - - 255
    - 255
    - 255
  - *id005
  - - 255
    - 255
    - 255
  - *id005
  - *id005
- - &id006
    - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - *id006
  - *id006
  - *id006
  - *id006
  - *id006
  - *id006
- - &id007
    - 0
    - 0
    - 0
  - *id007
  - *id007
  - *id007
  - *id007
  - - 255
    - 255
    - 255
  - *id007
  - *id007
- - &id008
    - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
  - *id008
intensity: 142
intensity_expt: 142
matrixdim:
- 8
- 8
picked:
- 165
- 255
- 76
update_fluoled_active: false
update_matrix_active: false
user:
- - &id009
    - 0
    - 0
    - 0
  - *id009
  - *id009
  - *id009
  - *id009
  - *id009
  - *id009
  - *id009
- - &id010
    - 0
    - 0
    - 0
  - *id010
  - *id010
  - *id010
  - *id010
  - *id010
  - *id010
  - *id010
- - &id011
    - 0
    - 0
    - 0
  - *id011
  - *id011
  - *id011
  - *id011
  - *id011
  - *id011
  - *id011
- - &id012
    - 0
    - 0
    - 0
  - *id012
  - *id012
  - *id012
  - *id012
  - *id012
  - *id012
  - *id012
- - &id013
    - 0
    - 0
    - 0
  - *id013
  - *id013
  - *id013
  - *id013
  - *id013
  - *id013
  - *id013
- - &id014
    - 0
    - 0
    - 0
  - *id014
  - *id014
  - *id014
  - *id014
  - *id014
  - *id014
  - *id014
- - &id015
    - 0
    - 0
    - 0
  - *id015
  - *id015
  - *id015
  - *id015
  - *id015
  - *id015
  - *id015
- - &id016
    - 0
    - 0
    - 0
  - *id016
  - *id016
  - *id016
  - *id016
  - *id016
  - *id016
  - *id016
